/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectsample.helloworld;

import javax.swing.JLabel;

/**
 *
 * @author Ela
 */
public class Forgot_Password_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_Password_Interface
     */
    public Forgot_Password_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        firstCard = new javax.swing.JPanel();
        upperText1 = new javax.swing.JLabel();
        upperText2 = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        emailAddressField = new javax.swing.JTextField();
        submitButtonBGPanel = new javax.swing.JPanel();
        submitLabel = new javax.swing.JLabel();
        emptyFieldErrorLabel = new javax.swing.JLabel();
        closeButtonBGPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        secondCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        continueButtonBGPanel = new javax.swing.JPanel();
        continueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        layeredPane.setPreferredSize(new java.awt.Dimension(376, 178));
        layeredPane.setLayout(new java.awt.CardLayout());

        firstCard.setBackground(new java.awt.Color(36, 25, 29));
        firstCard.setPreferredSize(new java.awt.Dimension(376, 178));

        upperText1.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText1.setForeground(new java.awt.Color(255, 255, 255));
        upperText1.setText("Enter your email address and we will send");

        upperText2.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText2.setForeground(new java.awt.Color(255, 255, 255));
        upperText2.setText("you a link to reset your password.");

        emailAddressLabel.setFont(new java.awt.Font("Avenir Light", 0, 12)); // NOI18N
        emailAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailAddressLabel.setText("Email address:");

        emailAddressField.setBackground(new java.awt.Color(105, 91, 96));
        emailAddressField.setFont(new java.awt.Font("Avenir Light", 0, 12)); // NOI18N
        emailAddressField.setForeground(new java.awt.Color(255, 255, 255));
        emailAddressField.setCaretColor(new java.awt.Color(255, 255, 255));

        submitButtonBGPanel.setBackground(new java.awt.Color(85, 119, 141));

        submitLabel.setFont(new java.awt.Font("Barlow Medium", 0, 14)); // NOI18N
        submitLabel.setForeground(new java.awt.Color(255, 255, 255));
        submitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitLabel.setText("SUBMIT");
        submitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout submitButtonBGPanelLayout = new javax.swing.GroupLayout(submitButtonBGPanel);
        submitButtonBGPanel.setLayout(submitButtonBGPanelLayout);
        submitButtonBGPanelLayout.setHorizontalGroup(
            submitButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        submitButtonBGPanelLayout.setVerticalGroup(
            submitButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        emptyFieldErrorLabel.setFont(new java.awt.Font("Avenir Light", 0, 12)); // NOI18N
        emptyFieldErrorLabel.setForeground(new java.awt.Color(255, 153, 102));
        emptyFieldErrorLabel.setText("Field cannot be blank.");

        closeButtonBGPanel.setBackground(new java.awt.Color(85, 119, 141));

        closeLabel.setFont(new java.awt.Font("Barlow Medium", 0, 14)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("CLOSE");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonBGPanelLayout = new javax.swing.GroupLayout(closeButtonBGPanel);
        closeButtonBGPanel.setLayout(closeButtonBGPanelLayout);
        closeButtonBGPanelLayout.setHorizontalGroup(
            closeButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
        closeButtonBGPanelLayout.setVerticalGroup(
            closeButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout firstCardLayout = new javax.swing.GroupLayout(firstCard);
        firstCard.setLayout(firstCardLayout);
        firstCardLayout.setHorizontalGroup(
            firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstCardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(upperText2)
                .addGap(83, 83, 83))
            .addGroup(firstCardLayout.createSequentialGroup()
                .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstCardLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(upperText1))
                    .addGroup(firstCardLayout.createSequentialGroup()
                        .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstCardLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(emailAddressLabel))
                            .addGroup(firstCardLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(closeButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstCardLayout.createSequentialGroup()
                                .addComponent(emptyFieldErrorLabel)
                                .addGap(0, 67, Short.MAX_VALUE))
                            .addComponent(emailAddressField))))
                .addGap(56, 56, 56))
            .addGroup(firstCardLayout.createSequentialGroup()
                .addGap(20, 283, Short.MAX_VALUE)
                .addComponent(submitButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        firstCardLayout.setVerticalGroup(
            firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstCardLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(upperText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperText2)
                .addGap(18, 18, 18)
                .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressLabel))
                .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstCardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emptyFieldErrorLabel))
                    .addGroup(firstCardLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(firstCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(closeButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        layeredPane.add(firstCard, "card2");

        secondCard.setBackground(new java.awt.Color(36, 25, 29));
        secondCard.setPreferredSize(new java.awt.Dimension(376, 178));

        jLabel1.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 109, 139));
        jLabel1.setText("CHECK YOUR MAIL");

        jLabel2.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("We have sent a password-recovery link to your email");

        jLabel3.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("address. The link is only valid for 24 hours.");

        continueButtonBGPanel.setBackground(new java.awt.Color(85, 119, 141));

        continueLabel.setForeground(new java.awt.Color(255, 255, 255));
        continueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueLabel.setText("CONTINUE");
        continueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continueLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continueLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout continueButtonBGPanelLayout = new javax.swing.GroupLayout(continueButtonBGPanel);
        continueButtonBGPanel.setLayout(continueButtonBGPanelLayout);
        continueButtonBGPanelLayout.setHorizontalGroup(
            continueButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        continueButtonBGPanelLayout.setVerticalGroup(
            continueButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout secondCardLayout = new javax.swing.GroupLayout(secondCard);
        secondCard.setLayout(secondCardLayout);
        secondCardLayout.setHorizontalGroup(
            secondCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondCardLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(secondCardLayout.createSequentialGroup()
                .addGroup(secondCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondCardLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(secondCardLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondCardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(continueButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        secondCardLayout.setVerticalGroup(
            secondCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondCardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(continueButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        layeredPane.add(secondCard, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitLabelMouseEntered
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(submitButtonBGPanel, "entered");
    }//GEN-LAST:event_submitLabelMouseEntered

    private void submitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitLabelMouseExited
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(submitButtonBGPanel, "exited");
    }//GEN-LAST:event_submitLabelMouseExited

    private void submitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitLabelMouseClicked
        // TODO add your handling code here:
        String emailAddress;
        emailAddress = emailAddressField.getText().trim();
        if (!(emailAddressField.getText()).isEmpty()) {
            if (!(emailAddress.contains("@")) || (emailAddress.contains(" ")))
                emptyFieldErrorLabel.setText("Invalid email address.");
            else
                Card.changeCard(layeredPane, secondCard);
        }
        else
            emptyFieldErrorLabel.setText("Field cannot be blank.");
        
    }//GEN-LAST:event_submitLabelMouseClicked

    private void continueLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLabelMouseEntered
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(continueButtonBGPanel, "entered");
    }//GEN-LAST:event_continueLabelMouseEntered

    private void continueLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLabelMouseExited
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(continueButtonBGPanel, "exited");
    }//GEN-LAST:event_continueLabelMouseExited

    private void continueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueLabelMouseClicked
        // TODO add your handling code here:
        Frame.exitFrame(this);
    }//GEN-LAST:event_continueLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        Frame.exitFrame(this);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(closeButtonBGPanel, "entered");
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(closeButtonBGPanel, "exited");
    }//GEN-LAST:event_closeLabelMouseExited
    
    public JLabel getErrorLabel() {
        return emptyFieldErrorLabel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closeButtonBGPanel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel continueButtonBGPanel;
    private javax.swing.JLabel continueLabel;
    private javax.swing.JTextField emailAddressField;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel emptyFieldErrorLabel;
    private javax.swing.JPanel firstCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JPanel secondCard;
    private javax.swing.JPanel submitButtonBGPanel;
    private javax.swing.JLabel submitLabel;
    private javax.swing.JLabel upperText1;
    private javax.swing.JLabel upperText2;
    // End of variables declaration//GEN-END:variables
}
