/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectsample.helloworld;

/**
 *
 * @author Ela
 */
public class Guide_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Guide_Interface
     */
    public Guide_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        BGPanel = new javax.swing.JPanel();
        upperText1 = new javax.swing.JLabel();
        upperText2 = new javax.swing.JLabel();
        upperText3 = new javax.swing.JLabel();
        upperText4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        okayButtonBGPanel = new javax.swing.JPanel();
        okayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BGPanel.setBackground(new java.awt.Color(36, 25, 29));

        upperText1.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText1.setForeground(new java.awt.Color(255, 255, 255));
        upperText1.setText("FAQ: Why are the last 3 addresses not");

        upperText2.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText2.setForeground(new java.awt.Color(255, 255, 255));
        upperText2.setText("editable?");

        upperText3.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText3.setForeground(new java.awt.Color(255, 255, 255));
        upperText3.setText("We are currently serving only inside Plaridel, Bulacan ");

        upperText4.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        upperText4.setForeground(new java.awt.Color(255, 255, 255));
        upperText4.setText("area. We are doing our best to reach out to more");

        jLabel5.setFont(new java.awt.Font("AvenirNext LT Pro Regular", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("people and their favorite cravings.");

        okayButtonBGPanel.setBackground(new java.awt.Color(85, 119, 141));

        okayLabel.setFont(new java.awt.Font("Barlow Medium", 0, 14)); // NOI18N
        okayLabel.setForeground(new java.awt.Color(255, 255, 255));
        okayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okayLabel.setText("GOT IT, THANKS!");
        okayLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okayLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okayLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okayLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout okayButtonBGPanelLayout = new javax.swing.GroupLayout(okayButtonBGPanel);
        okayButtonBGPanel.setLayout(okayButtonBGPanelLayout);
        okayButtonBGPanelLayout.setHorizontalGroup(
            okayButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        okayButtonBGPanelLayout.setVerticalGroup(
            okayButtonBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(upperText4)
                .addGap(32, 32, 32))
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okayButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BGPanelLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(upperText1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                                    .addComponent(upperText2)
                                    .addGap(91, 91, 91))))
                        .addGroup(BGPanelLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(upperText3))
                        .addGroup(BGPanelLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel5))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(upperText1)
                .addGap(2, 2, 2)
                .addComponent(upperText2)
                .addGap(18, 18, 18)
                .addComponent(upperText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperText4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(okayButtonBGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layeredPane.setLayer(BGPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayLabelMouseClicked
        // TODO add your handling code here:
        Frame.exitFrame(this);
    }//GEN-LAST:event_okayLabelMouseClicked

    private void okayLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayLabelMouseEntered
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(okayButtonBGPanel, "entered");
    }//GEN-LAST:event_okayLabelMouseEntered

    private void okayLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayLabelMouseExited
        // TODO add your handling code here:
        Colour.setToSecondaryButtonColor(okayButtonBGPanel, "exited");
    }//GEN-LAST:event_okayLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guide_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guide_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guide_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guide_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guide_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JPanel okayButtonBGPanel;
    private javax.swing.JLabel okayLabel;
    private javax.swing.JLabel upperText1;
    private javax.swing.JLabel upperText2;
    private javax.swing.JLabel upperText3;
    private javax.swing.JLabel upperText4;
    // End of variables declaration//GEN-END:variables
}
